name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm ci --omit=optional
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          INJECT_PGP_SIGNATURE=true npm run build
          tar czf datagarden-$GITHUB_REF_NAME.tar.gz -C build .
        env:
          REACT_APP_API_BASE_PATH: ${{ vars.API_BASEPATH }}
          REACT_APP_CONTENT_HOST: ${{ vars.CONTENT_BASEPATH }}
          REACT_APP_WS_BASE_PATH: ${{ vars.WS_BASEPATH }}
          REACT_APP_SENTRY_URL: ${{ vars.SENTRY_URL }}
          REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          REACT_APP_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: build
      - name: Publish release
        run: gh release create $GITHUB_REF_NAME datagarden-$GITHUB_REF_NAME.tar.gz datagarden-$GITHUB_REF_NAME.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: production-build
          path: build
      - name: Upload to S3
        run: |
          aws s3 sync build s3://$S3_BUCKET/ --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}

