name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          npm run build
          tar czf datagarden-$GITHUB_REF_NAME.tar.gz -C build .
        env:
          API_BASEPATH: ${{ env.API_BASEPATH }}
          CONTENT_BASEPATH: ${{ env.CONTENT_BASEPATH }}
          WS_BASEPATH: ${{ env.WS_BASEPATH }}
      - name: Publish release
        run: gh release create $GITHUB_REF_NAME datagarden-$GITHUB_REF_NAME.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

